### ISSUE TITLE
"accepted" / "stay tuned" status before SRPM build starts

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#1038]
When asking  @martinpitt and @marusak about their expectations they both suggested it would be nice to have some "accepted" / "stay tuned" status, which would appear "immediately" and be replaced with "Building SRPM" later.

Martin:
In one case, creating the packit statuses in a GitHub PR took unusually long (> 5 mins), which made me nervous and ping Tomas, as usually the statuses get created rather quickly. I think that kind of "I heard you" feedback is quite important.

Matej:
I agree with Martin that packit should be reasonably quick to post status to Github - just to let us know it was recognized and it will be dealt with. This should be measured in "a couple of seconds". I would assume there is some queue where you keep tasks that will be run. If that is the case, then I would say there should be some limit on how much time a task spends in a queue waiting for a free worker. While posting status should take at most a couple of seconds, this should take a maximum of "a couple of minutes" and then the task should be running.

**Comment by lachmanfrantisek** [comment]
I definitely agree with this. Just a few implementation details:

* To not introduce a new status, we should use the ones for each target (that will be used for build progress) => We need to have a config parsed in that time.
* Since we already have one initial celery task for determining/planning real celery tasks, we can do that here or as another celery task that will send a `pending` state and submit the follow-up task.
* If we want to reduce the number of statuses, that's a different story and will require much more planning (representation options on all platforms,  contradicting user opinions,...) Let's not discuss that here.
