### ISSUE TITLE
secrets: read selected GitHub secrets and forward them to TFT

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1122]
1. Make sure this actually works: we can read those secrets: https://docs.github.com/en/rest/reference/actions#secrets

2. Once verified, packit-service should read selected GitHub secrets and forward them to TFT.
 * TFT tracking card: TBD
 * TMT tracking card: TBD

3. We should design and agree on how this would be configured (allowlist for secrets? read and forward all by default? globbing?)

**Comment by thrix** [comment]
And discuss also: variable masking

**Comment by ZhukovGreen** [comment]
I believe that's fine to load all GitHub secrets to tmt

**Comment by lachmanfrantisek** [comment]
On our team meeting and the meeting with TF and convert2rhel, we've discussed the possibilities and here is a short outcome from it:

* Using GitHub secrets is not possible from the GitHub application. We can get secrets only in an encrypted form without being able to get the key.
* Here are the possibilities:
  * **Using GitHub actions where the secrets are available => various options exist here, we want to spend some time investigating this generally:** #1097
  * Implement this on GitLab where using variables is possible (no users interested in this on GitLab)
  * We don't want to be responsible for storing keys on our side.
  * We might support some 3rd party secrets provider.
  * **Leave it to TF => since the benefit of GitHub secrets cannot be used, we don't need to be a man-in-the-middle here.**
* convert2rhel has a workaround so we don't need to solve this now and will meet in a month (you should have received the invite) to discuss the alternative implementation. In the meantime, the TF team will take a look at how they can do it on their side, Packit team will spend some time on the GitHub actions investigation.

I'm going to close this issue since we have already an issue for GitHub actions and we can create specific issues later on.
