### ISSUE TITLE
Make it shorter to get to the test results

### ISSUE THREAD

**Issue by psss** [packit/packit-service#1178]
When github checks are enabled, check [results page](https://github.com/psss/tmt/pull/795/checks?check_run_id=3182856758) contains a link to [packit page](https://dashboard.packit.dev/results/testing-farm/32270) which contains a link to actual test results. This is three clicks. Could you please make the path shorter? Thanks.

**Comment by lachmanfrantisek** [comment]
I agree that it is annoying for the people interested only in the TF results.

If we want to use checks, we can't do anything about the first click (from the statuses, or by clicking to the `Checks` tab).

Just for context, here are the reasons why we want to link our page instead of TF directly:
* to have some control over the page we link (when TF does not work or returns something unexpected)
* to link the build and test so users can easily browse the relevant results on our dashboard (improve the browsing through the dashboard is an ongoing effort for this month)
* consistency (we don't link `Copr`/`Koji` as well)
* to not confuse newcomers (there is an installability-test enabled by default and new users were confused by a different page they ended on)

Luckily, with checks, we can provide markdown descriptions that can contain multiple links. I would not like to duplicate the whole dashboard page, but adding a TF link shouldn't be hard to do. Will this work for you?

**Comment by psss** [comment]
Thanks for the clarification.

> adding a TF link there shouldn't be hard to do. Will this work for you?

Yeah, removing one extra click would be helpful.

**Comment by csomh** [comment]
> I would not like to duplicate the whole dashboard page, but adding a TF link there shouldn't be hard to do.

I'm wondering if it wouldn't be better to actually do just that. In the time of commit checks the dashboard page was needed b/c there was no other place to show that information. But with the new checks API, there is actually this page on GitHub on which all this information could be presented. I think doing this could also offer a more coherent experience for users.

**Comment by lachmanfrantisek** [comment]
I was thinking about that for a while but this lacks the connection between results (*Get the build for this test.*, *Find SRPM log for this build/test.*, *Find all the builds for this project/PR/...*)... 

But there is a huge benefit of no need to store the info in the database.

I am really not sure. Having everything in checks sounds easy and quick but we can't have everything there so we will have actually two interfaces...

I would start with the test URL and see if someone else would be interested in more info there.

**Comment by TomasTomecek** [comment]
I'm wondering if we could include logs in the github checks page since those are the most important piece of the info together with the overall status 

+1 Franta for keeping dashboard as it is, you're right it's forge-independent

Since the checks status page is markdown-only, we are limited in terms of visuals, but including links, and even logs, would be a great benefit.

**Comment by psss** [comment]
One more related thing I noticed today: When the copr build is still in progress it would be nice to have a link from the check page to see more details about the progress. Currently there's just a link to packit docs which does not help.

**Comment by mfocko** [comment]
@psss I have seen the exception in sentry, that status would've been replaced if the build had been submitted correctly.
