### ISSUE TITLE
Database: models for group of chroots

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1327]
Follow-up for: https://github.com/packit/research/pull/128

We need to store information about a group of related chroot-builds that were triggered together.

* [ ] Create a new model for each type (Koji, Copr, TF) with a clear name
* [ ] Provide a migration script that tries to group the already present chroot models (by Copr build id, timestamp, ...)
* [ ] Improve/enhance/fix the API endpoint to be able to show both chroot-info and grouped-info.
* [ ] Make sure that the newly created models are utilized in the existing code base

**Comment by FrNecas** [comment]
Result from today's discussion on Fedora chat about model naming, there is a slight change from the initial research doc, the naming should be explicit so using `Group` inside the grouped model name seems to be the best way to go. For example, `CoprBuildTarget` will represent a single build in copr (the word target is used instead of chroot for more clarity) and `CoprBuildGroup` for the grouping model. Similarly for TF & Koji

**Comment by nikromen** [comment]
When providing the database scheme (the first subtask) you can get inspired by ProposeDownstreamModel - ProposeDownstreamTargetModel scheme.
