### ISSUE TITLE
Allow repository contributors to use Packit commands in comments

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1423]
Currently Packit accepts commands only from the author of the PR or a user with write access in the target repository.

There is a request to extend this also to users, who are regular contributors to the repository.

The "contributor" status told by GitHub could be used for this, which would mean, that anyone who has a commit merged in the repo could use Packit commands to re-run builds and tests.

This should **not** be extended to 'propose-downstream'.

**Comment by kkaarreell** [comment]
Please, ideally make it configurable in `.packit.yaml`.

**Comment by lachmanfrantisek** [comment]
> Please, ideally make it configurable in `.packit.yaml`.

That can be a bit tricky since the config can be changed in the PR, but it's not such a big issue since we are discussing the difference between anyone and someone with at least some relation to the project. (We can also provide some allowlist, but that has the same issue and need to be maintained.)

**Comment by kkaarreell** [comment]
> That can be a bit tricky since the config can be changed in the PR

I don't see it as an issue. This RFE should primarily address Packit test rescheduling in someone else's PRs.
