### ISSUE TITLE
Implement retriggering the downstream jobs via issue comments in issue_repository

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1536]
Implement retriggering downstream Koji build and Bodhi update jobs via issue comments in issues in `issue_repository` specified by the user:
- [ ] retriggering will be done via dedicated Packit commands - e.g `/packit koji-build` `/packit bodhi-update`
- [ ] the handling should be very similar to `/packit propose-downstream`
- [ ] the user needs to enable Packit app on the `issue_repostitory` so that we get the comment events => update the docs with this requirement
- [ ] user who triggers the jobs should be allowlisted - write access to `issue_repository` is required - update the docs so that users know about this when setting `issue_repository`

**Comment by ochosi** [comment]
Adding a comment in an upstream issue is only helpful/possible, when an issue actually gets created.
Currently with osbuild/osbuild-composer we're in a situation where our koji builds don't get triggered and there is no exception thrown in packit, so no issue gets created.

In such cases it would seem more logical to be able to (re-)trigger the koji build from the associated downstream PR (since that is also what triggers the koji build in the first place).

**Comment by lbarcziova** [comment]
@ochosi that's true and we already have an issue for that as well, #1537, which is planned to be implemented first.

**Comment by TomasTomecek** [comment]
Just a note that we discussed how would Packit know what exactly it should do: which downstream package and what branch. We concluded that the issue should contain the info in a human-readable form and Packit should parse it.
