### ISSUE TITLE
Packit creates issues upstream despite everything being ok

### ISSUE THREAD

**Issue by ochosi** [packit/packit-service#1580]
We recently noticed that packit creates tickets in our upstream repository, saying it failed to create a PR downstream while it clearly did.
Not sure what causes this hickup - maybe the timeout between creating the PR and checking if it's actually there is too short because pagure is slow..?

Here are some examples:

1. https://github.com/osbuild/osbuild-composer/issues/2829 -> https://src.fedoraproject.org/rpms/osbuild-composer/pull-request/33
2. https://github.com/osbuild/osbuild-composer/issues/2783 -> https://src.fedoraproject.org/rpms/osbuild-composer/pull-request/30

**Comment by TomasTomecek** [comment]
I hope we'll be able to reproduce and fix the root cause.

Nevertheless, we should correctly clean the working tree when Packit checks out a new dist-git branch to prepare the update.

Details:
```
Cmd('git') failed due to: exit code(1) cmdline: git checkout main stderr: 'error: Your local changes to the following files would be overwritten by checkout: osbuild-composer.spec Please commit your changes or stash them before you switch branches. Aborting'
```

**Comment by majamassarini** [comment]
> Nevertheless, we should correctly clean the working tree when Packit checks out a new dist-git branch to prepare the update.
> ```
> Cmd('git') failed due to: exit code(1) cmdline: git checkout main stderr: 'error: Your local changes to the following files would be overwritten by checkout: osbuild-composer.spec Please commit your changes or stash them before you switch branches. Aborting'
> ```

I think the root cause of this problem is the use of an action which is modifying the working directory

`.packit.yaml` ref https://github.com/osbuild/osbuild-composer/blob/main/tools/rpm_spec_add_provides_bundle.sh#L11

```
actions:
  get-current-version: bash -c "git describe --tags --abbrev=0 | sed 's|v||'"
  post-upstream-clone: "./tools/rpm_spec_add_provides_bundle.sh"
```

Are we sure that we want to cleanup the work done by the action? Maybe we should just give back a warning to the user?

I am trying to reproduce it locally but I think this is the issue.

**Comment by TomasTomecek** [comment]
That's a pretty good point Maja: should we rerun all the actions to get a consistent repo state after switching branches?

**Comment by majamassarini** [comment]
Yes, you are right, probably we should do that.
I think we should both rerun actions and leave for the user a warning.

**Comment by lbarcziova** [comment]
So if I understand the problem correctly, this is about the action running in the clone of the upstream repo which changes the upstream specfile that is used as a source for doing changes to the downstream specfile. So since the checkout causing the exception is being done after the PR in dist-git is created, is it really needed to rerun the actions? Couldn't we only do the force checkout (=> throw away the changes done in the upstream repo)?

**Comment by majamassarini** [comment]
I need to replicate it locally. I am not totally sure we are not doing any other job with that sources. Probably you are right. I have not yet had time to setup a test, I will do that when I am back.

**Comment by majamassarini** [comment]
> So if I understand the problem correctly, this is about the action running in the clone of the upstream repo which changes the upstream specfile that is used as a source for doing changes to the downstream specfile. So since the checkout causing the exception is being done after the PR in dist-git is created, is it really needed to rerun the actions? Couldn't we only do the force checkout (=> throw away the changes done in the upstream repo)?

I think you are right, we do not need to replicate any action, since the exception is thrown by the `finally` statement (https://github.com/packit/packit/blob/main/packit/api.py#L861) which should clean up the working dir.
