### ISSUE TITLE
Packit complains that our notifications repo doesn't have a config

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1592]
https://github.com/packit/notifications/issues/453

This breaks the automatic verifications.

**Comment by nikromen** [comment]
It seems to be caused because of a typo in user's command. In `/packit verify-fs jkozol` there should be `verify-fas` instead of `verify-fs`. But the way how service behaves is weird. We should ignore this command (as you can see there is no 👀 emoji on the [command](https://github.com/packit/notifications/issues/451#issuecomment-1193981250))

**Comment by TomasTomecek** [comment]
Some sort of special treatment for the notifications repo would be appreciated.
