### ISSUE TITLE
Identifier ignored for re-run?

### ISSUE THREAD

**Issue by lukaszachy** [packit/packit-service#1625]
Hi,
in tmt we have 3 fedora-36 jobs. 
One is from target: fedora-all, other two from target: fedora-latest-stable. To have them distinguishable the later contain  `identifier: XXX`.

From reporting PoV all is good - I can see which job is which. However if I click 're-run' next to `testing-farm:fedora-36-x86_64:internal-wow` all 3 fedora-36 jobs are re-run.

How can one reschedule only selected one?

**Comment by lbarcziova** [comment]
Hi!

Thanks for creating an issue. I think this was meant to work (retriggering for a specific job via `re-run` button) and also there is currently no other option to retrigger only selected target+identifier, so we definitely need to take a look into this. Could you please point us to your Packit configuration so that we can try to reproduce this?

**Comment by lukaszachy** [comment]
Sure - https://github.com/teemtee/tmt/blob/main/.packit.yaml

**Comment by lbarcziova** [comment]
Thanks! So I just reproduced this and it is definitely a bug on our side. I will include this in our next planning meeting.
