### ISSUE TITLE
[BUG] Race condition when building SRPM vs binary RPMs in Copr

### ISSUE THREAD

**Issue by webknjaz** [packit/packit-service#1661]
_(this time, I hope this is the right repo)_

So I noticed an interesting side effect of actively working on `.packit.yml` in a PR. At some point I was able to make it work and both SRPM and testing stage completed successfully. As I was playing around, I got into a situation where an SRPM build succeeded but testing failed because of a change in the following commit. So basically SRPM used `HEAD^` for checkout (the last one in the PR at the time). While it was still in progress, a new commit (`HEAD`) appeared and when SRPM succeeded (with the right commit), the testing stage jobs started, but checked out a different commit (the last one in the PR at the time) and failed because of the difference in the `.packit.yml` file (the last commit broke something).

I think that Packit should behave like other CIs and use the same commit that other jobs in the same workflow run use. I would expect that the commit with the proper config would have a green status reported and the broken commit would be red. What I saw was both commits turning red.

Unfortunately, I haven't kept the logs but I hope this gives you some idea of what's been happening.

**Comment by lbarcziova** [comment]
Hi! Thank you for creating an issue. 

Just to check and avoid confusion, are we talking, as the title says, about a race condition between SRPM and RPM builds where these 2 were working with different commits or RPM build job and test (Testing Farm) job? And if it's the first case, are you building your SRPMs in Copr (or with the old solution - in our infra)?

**Comment by webknjaz** [comment]
I think it must be the first case but I'm not sure, since I don't remember whether this was before or after I enabled Copr. I'm almost sure that it was after, though.

**Comment by TomasTomecek** [comment]
@webknjaz this is a good point. If we are using PR ID as an identifier, then the latest commit is always used and can lead to inconsistent results. Agreed that we should point to commit SHA.

**Comment by mfocko** [comment]
How to **try** to reproduce:

1. Create a new test in packit/hello-world
2. Trigger Copr build and test
3. Before Copr build is finished, push a new commit that would break the tests
4. TF _should_ be triggered with the commit that was used for Copr build

**Comment by TomasTomecek** [comment]
I just verified that Packit already pairs Copr RPM builds with Testing Farm runs using either commit ID or a specific build - not using PR refs:

https://github.com/packit/packit-service/blob/6f648528db0535b9bf798b814efb74a5fc895139/packit_service/worker/handlers/testing_farm.py#L139-L144

We are also planning to rework the relationship between copr_build and tests jobs that will completely change the codepaths: 
https://github.com/packit/packit-service/issues/1775

Therefore I'm closing this as done. Please reopen if you find a deterministic set of steps that lead to a race condition. Otherwise it's really hard to investigate and fix races.
