### ISSUE TITLE
Failed test (testing farm job) not shown in packit dashboard

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#1665]
While I was analyzing issue packit-service#1664 I realized that the failed job `testing-farm:fedora-37-x86_64` was not shown in packit dashboard, only the successfull testing farm jobs were shown.

**Comment by lbarcziova** [comment]
The reason is that we create the models in DB just after successful submitting the tests to TF, so in this case, we don't create a DB record for the particular target. IIRC, we do the same with Copr builds - create the DB records just after submitting the builds in Copr. Do you think we should adjust this behaviour?

**Comment by majamassarini** [comment]
If we think it is doable to enhance it probably it is worth spending some time on it.
I use the dashboard as a overall view to see if everything is going smooth... if problems are not shown then probably it becomes less usefull, at least for me.

**Comment by lbarcziova** [comment]
I get your point. This is definitely something to discuss as a team because the current implementation also makes sense if you think about it in the way that the state of the job is tracked only after successful submission => failure/error states mean some actual failure in the execution of build/tests and if the job is not in the database it means that the job was not executed at all because of some failed preconditions (invalid configuration, ...).

**Comment by FrNecas** [comment]
Outcome from today's arch discussion: we should store the model in DB even if TF submission fails (same for other types of targets). As for retries, we should have one model instance per test (avoid creating a new model when retrying). Henceforth, we need to track the retry status in the model as well (something similar should already be in propose-downstream most likely).

I will try to take care of this issue since it is a blocker for #1633
