### ISSUE TITLE
Make sure all the handlers are idempotent

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1692]
* [ ] Make sure every handler can be re-triggered in any state of the execution.
  * [ ] Fix the easy problems.
  * [ ] Create issues for the more complicated problems.

**Comment by lbarcziova** [comment]
Some notes regarding what actions are done in the handlers code and potential improvements:

Firstly we have the handlers that report the state of the task to the user and only update the state of existing models in DB (+ in some, we are doing GET requests to get e.g. end time of the Copr build). As for the reporting, as discussed, creating the commit statuses/checks is almost idempotent (there is only different timestamp on the check) and as for commenting, we have methods that check existing duplicate comments.

1. KojiTaskReportHandler
2. KojiBuildReportHandler
3. TestingFarmResultsHandler
4. VMImageBuildResultHandler
5. CoprBuildStartHandler
6. CoprBuildEndHandler - here is an extra step: creating TF handler task(s)
-----------------------------------
these 2 are just a little bit different, they are **creating** or updating the DB entries
7. GithubAppInstallationHandler
8. GithubFasVerificationHandler


- in these, the code could be updated so that in the beginning, we always check whether the state in DB is different than the one about to report and update the state in DB at the end of the handler code; the CoprBuildEndHandler could be problematic because of the creation of TF handler task(s).

Then, there are tasks where we are making POST requests to external services, creating new models in the DB, ... I think with these, we cannot make many improvements:

1. DownstreamKojiBuildHandler - submitting build in Koji
2. CoprBuildHandler - submitting build in Copr
3. TestingFarmHandler - submitting TF run
4. BodhiUpdateHandler - submitting updates in Bodhi
5. KojiBuildHandler - submitting build in Koji
6. VMImageBuildHandler - submitting the image build
------------------------------------------------
9.  AbstractSyncReleaseHandler - this one is a little bit different; we are uploading new sources (if not present) and then doing changes on Git repo (using a deterministic branch) and, in the end, force pushing.

**Comment by TomasTomecek** [comment]
The question to me seems what do we do when a network error happens while submitting a build: do we submit another one? do we check if there is a pending one a reuse it?

**Comment by lbarcziova** [comment]
As we were discussing during the last week's architecture that, we could decide for some handlers to not ensure the idempotency (and when implementing the mentioned Celery `acks_late` do not mark these). 

In my opinion, for the second group (the 7. may be an exception), changing all the submitting code to check already existing submissions and make these also consistent with the database would require much more complex solution to do it correctly and personally, I would currently not go that way.
After implementing #1328, this could be maybe easier.

WDYT?

**Comment by TomasTomecek** [comment]
> As we were discussing during the last week's architecture that, we could decide for some handlers to not ensure the idempotency (and when implementing the mentioned Celery `acks_late` do not mark these).

Ah, right! Forgot about it. We can totally do that incrementally.

> In my opinion, for the second group (the 7. may be an exception), changing all the submitting code to check already existing submissions and make these also consistent with the database would require much more complex solution to do it correctly and personally, I would currently not go that way. After implementing #1328, this could be maybe easier.
> 
> WDYT?

Yes agreed. Retrying manually or using the mechanism we already have in place sounds the current path forward.

**Comment by lachmanfrantisek** [comment]
@lbarcziova Thanks for finishing this! Since the PR is merged, can we mark some handlers with `acks_late`?
