### ISSUE TITLE
Add possibility to define custom tmt contexts in .packit.yaml

### ISSUE THREAD

**Issue by kkaarreell** [packit/packit-service#1797]
It would be handy to be able to define custom tmt context in .packit.yaml so that this context is then set for all testing-farm jobs.

**Comment by FrNecas** [comment]
@kkaarreell I guess this is not urgent since your problem will be resolved by dropping the default dynamic ref path, right? But lets keep this issue open, it seems nice to have.

**Comment by kkaarreell** [comment]
Right, not urgent

**Comment by kkaarreell** [comment]
@FrNecas Hi, I have another use case for the RFE. I could use that extra context specified by Packit for test plan filtering.. so I don't have to run all existing plans in Packit CI. That would be IMHO really handy.

**Comment by TomasTomecek** [comment]
Guys, please define the action items here so it's clear to all of us what exactly should be done :)

I understand this that we just need to add new tmt option in packit.yaml.

**Comment by kkaarreell** [comment]
I am sorry, I though it is clear. :-) The request is to extend .packit.yaml definition with a section where a user could specify custom tmt context that would be passed to all testing-farm requests and possibly used in test plans to do some adjustments.
For example, I could use such context to identify rust triggered by Packit CI for my project and selectively enable/disable tmt test plans etc.

**Comment by kkaarreell** [comment]
But I am not rushing on it, please take your time to discuss it with other stakeholders.. it was just an idea. :-)

**Comment by TomasTomecek** [comment]
Thank you!

We can put this issue in the bucket of "implement new variable for TF": https://github.com/packit/packit-service/issues/1627

**Comment by r0x0d** [comment]
Posting my comment here to say that this feature would indeed be helpful for [oamg/leapp](https://github.com/oamg/leapp) and [oamg/convert2rhel](https://github.com/oamg/convert2rhel) and the reason are: 

- Leapp currently overrides the distro-name when sending the requests to tmt (see: https://github.com/oamg/leapp/blob/master/.github/workflows/reuse-tests-7to8.yml#L29-L31), and currently, we are facing a dilemma with going through with the implementation of packit that is: 
  - "Should we update our tests workflow to adapt to the distro name that packit sends, or should we wait for them to provide a better way of overriding that setting?"
- Convert2RHEL will set up in the future some tests that will need to be triggered using a GitHub actions (mainly because of secrets management) and it would be nice to control this using custom contexts as well, this way, we can prevent some crazy hard configuration on our side to figure out whether to run the test or not. 

@FrNecas and @TomasTomecek are aware of this conversation as well, so if any extra context is needed, feel free to contact me for more insights!

**Comment by FrNecas** [comment]
The outcome of architecture: user context will override our defaults (including distro and others).

**Comment by r0x0d** [comment]
Hi, @FrNecas! We are trying to use this feature in https://github.com/oamg/leapp/pull/804, but it seems that the context is not being applied to the `tmt` call.  

See the error here: https://github.com/oamg/leapp/pull/804/checks?check_run_id=11172161654 

We think that the command is supposed to be: 

```bash
tmt --context distro=rhel-7.9 plan ls --filter enabled:true '^(?!.*upgrade_plugin)(?!.*tier[2-3].*)(?!.*rhsm)(?!.*c2r)(?!.*sap)(?!.*8to9)(.*e2e)'
```

Do you have any insights on what's probably going on there?

**Comment by FrNecas** [comment]
Hello @r0x0d , thanks for the report. From the Testing Farm log, it seems that Testing Farm first lists out plans using `tmt plan ls` but during this step the context that we pass to TF is not used (otherwise there would be not just `distro=rhel-7.9` but also keys like `arch` or `trigger`. Seems like a possible bug in Testing Farm, however it may be intentional (I am not sure). @thrix could you please confirm this?

**Comment by FrNecas** [comment]
So Testing Farm handles things correctly, so does packit. The problem in the linked PR is indentation - YAML is whitespace sensitive. Therefore

```yaml
  tf_extra_params:
    environments:
      - tmt:
        context:
          distro: "rhel-7.9"
```

was interpreted as tmt: null, rather than tmt: {context: ...}. Extra indentation is required. I am not sure if we can make this somehow more intuitive.

**Comment by r0x0d** [comment]
> So Testing Farm handles things correctly, so does packit. The problem in the linked PR is indentation - YAML is whitespace sensitive. Therefore
> 
> ```yaml
>   tf_extra_params:
>     environments:
>       - tmt:
>         context:
>           distro: "rhel-7.9"
> ```
> 
> was interpreted as tmt: null, rather than tmt: {context: ...}. Extra indentation is required. I am not sure if we can make this somehow more intuitive.

Oh, god! Thank you so much, @FrNecas! I will modify the config to be in accordance with this. For sure, I didn't know that YAML was whitespace sensitive. 

The more you break stuff, the more you know, I guess :D.
