### ISSUE TITLE
Pull request merged without required tests passing

### ISSUE THREAD

**Issue by psss** [packit/packit-service#1910]
A recent [pull request](https://github.com/teemtee/tmt/pull/1847) has been auto-merged before any tests passed. This seems to be caused by the fact that it was created from a fork so we get `can't run tests (and builds) internally` instead of actual testing. The check summary says `15 checks passed` which might be the cause of the confusion. Shouldn't `packit` use some different check status when tests cannot be run? I guess this would prevent the `auto-merge` feature skipping the required checks.

**Comment by TomasTomecek** [comment]
Hi, thank you for the bug report. I can confirm Packit **does not** set :heavy_check_mark: when it cannot run tests:

https://github.com/packit/packit-service/blob/eb5d95cdc1c1531ac27cc8dd5999ae310b06f2c5/packit_service/worker/checker/testing_farm.py#L83

It uses the neutral status:

![image](https://user-images.githubusercontent.com/1662493/218735578-0e838d46-f64d-448a-8853-09e07562db34.png)

What you are seeing right now in the pull request is the consequence of the `/packit build` comment done by a repo collaborator: https://github.com/teemtee/tmt/pull/1847#issuecomment-1427939144

Hence `15 checks passed` and you can inspect they are genuine test runs.

Please suggest what we can do better in Packit to make this more straightforward. At minimum we should document how to use Packit and Testing Farm together with GitHub's merge queue.

I recommend setting required set of checks to be passing for the auto-merge. @mfocko is working on adding support for this in Packit: https://github.com/packit/packit-service/pull/1909

**Comment by psss** [comment]
> I recommend setting required set of checks to be passing for the auto-merge.

The weird thing is that we have defined a set of required checks, but in this case they were somehow skipped. Could it be that when `/packit build` was called the checks were reset and because `pre-commit` was green the `auto-merge` happened? Still, I would expect that merging should not happen before all required checks are ok. Interesting...

**Comment by mfocko** [comment]
I don't think it should merge, if you don't have the checks, it just waits, e.g. in our case we tried _merge queue_, Zuul ignored the branch it created for the CI checks and it timed out. It needs to have them there…

The issue I mentioned in the PR, regarding auto-merge ignoring required checks and merging anyways while having a _merge queue_ enabled, could be related even though you don't have the _merge queue_ enabled.

I'm not sure how I feel about auto-merge being enabled given that GitHub tends to test their changes in production environment before rolling them out. (IIRC they even made a blog about the way they can route between deployed changes just to test them on production)

**Comment by mfocko** [comment]
## Revisiting the issue

I've gone through the docs:
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks

Overall I cannot find **any** comments about the results that are accepted as _successful_, so we can only _assume_ that `neutral` is accepted as successful which makes sense in case of code analysis tools or other CIs like that. OTOH we've already had a request to report issues with privileges as neutral as they are, technically, not failures (we didn't run anything). In the linked PR it is a problem, because it allowed bypassing the test runs on auto-merge.

If this problem affects you regularly, please let us know. One of the possible solutions to this problem would be configurable result for the permission issues, or maybe an option denoting that the check is _required_, so it should either succeed, or fail.

**Comment by mfocko** [comment]
The only `.skipped` I `rg`'d  in the Packit Service is related to the release-syncing (propose-downstream).

OTOH, reading the Slack discussion, I'm not really sure if this is something that should be _worked around_ on our side, as it is something that definitely affects other users of different CI systems too. I also hate the fact that the documentation is not **explicit** on this matter, cause I also got lost there (as can be seen in my previous comment).

**Comment by lbarcziova** [comment]
> But Packit is not using skipped, right? I don't see any neutral mentioned in the docs. So it's all a bit confusing to me.

No, we use `neutral` (see `conclusion` values in [here](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run)).


The behaviour is definitely not clear, also see [another related discussion](https://github.com/orgs/community/discussions/24754).

**Comment by psss** [comment]
To clarify more, so... even if the job is not completed, for example when I used `/packit test` in the pull request above, the `neutral` conclusion is used for the testing jobs? Wouldn't it be more appropriate to use one of the `status` values?

    Can be one of: queued, in_progress, completed, waiting, requested, pending

@lachmanfrantisek mentioned `pending` in the chat, which would make sense to me as well. Isn't the core of the problem not to mark the job as completed, or in other word to set the `conclusion` before we actually get the results?

**Comment by lbarcziova** [comment]
> To clarify more, so... even if the job is not completed, for example when I used /packit test in the pull request above, the neutral conclusion is used for the testing jobs? Wouldn't it be more appropriate to use one of the status values?

Yes, that's correct. This originated from #760 and the idea was not to make the PR "red" (CI failure) for permission issues (and now also for some missing prerequisites issues). I can see that for your use case (and possibly also other projects), this is not desired with the auto-merge. We could either verify that `pending` doesn't break anyone's use case or make it configurable as already suggested in the linked issue.
