### ISSUE TITLE
Enable installing additional packages from Copr repos in TF tests

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1972]
This is different solution to https://github.com/packit/packit-service/issues/1968 (and I believe more convenient).

As @fernflower explains in her table here: https://github.com/packit/packit-service/issues/1968#issuecomment-1480936760

The leapp team needs to request installation of leapp-repo in the tests for leapp explicitly in the TF request. Specifying this in the fmf metadata is not an option.

We already have logic for all of this and I naively thought one could specify this via `tf_extra_params`. Sadly one of the required fields is Copr build ID: https://testing-farm.gitlab.io/api/#operation/requestsPost

The ask here is to have a field in packit.yaml to define additional packages to install from specific Copr projects.

Context: https://github.com/oamg/leapp/pull/804/files#diff-2b4300f6d69654fd71c0cdd329b5a5f13fa8fe7eb709c76276bdfd3ea1dde578

**Comment by TomasTomecek** [comment]
Notes from a meeting with the leapp team:
- On demand testing should override the default testing
- Set the additional RPMs via a new config option "additional_artifacts"
- Capturing the dependency via fmf or rpm spec file would cause too many complications for leapp team
- @pirat89 suggested to parametrize configuration and be able to change it via `/packit {test,build} variable=value`.

**Comment by lbarcziova** [comment]
Just some notes as I am thinking about this:
- in TF payload, we need to specify the Copr build ID + chroot + package NVRs
- since the leapp/leapp repository build both PRs and commits in the same Copr repo, specifying the Copr repository in Packit config alone is not sufficient
-  we could make the [current logic](https://github.com/packit/packit-service/blob/1abb73381d16bebd85983607110fa7fe014e84e9/packit_service/worker/helpers/testing_farm.py#L998) of getting additional builds generic (currently works only with PRs from DB):
   1. this would require the builds to be built by Packit (same as for the comment command)
   2. the Packit config would need to contain the git repo namespace+name and branch/release

- if we want to allow this for any Copr builds (not only built by Packit), this would probably require some more hacky solution (regex filtering of built packages?)

WDYT @TomasTomecek @lachmanfrantisek ?

**Comment by TomasTomecek** [comment]
+1 regex filtering sounds like the most flexible solution

if we do it right, we could also reuse it for arguments to `/packit ...` comments

**Comment by lachmanfrantisek** [comment]
> * since the leapp/leapp repository build both PRs and commits in the same Copr repo, specifying the Copr repository in Packit config alone is not sufficient

I think it would be better for them to replace this with `additional_repo` to layer the new build on top of it, but don't change the project itself. You don't want to affect the repo with unmerged changes.

**Comment by TomasTomecek** [comment]
That would work but we still need to add the additional packages to the payload for testing farm, that's the main ask here

**Comment by TomasTomecek** [comment]
TODO:
- [ ] utilize `tf_extra_params` and set `environments -> artifacts -> type: repository` docs: https://testing-farm.gitlab.io/api/#operation/requestsPost
- [ ] if that doesn't work, implement this in Packit via a new option additional_artifacts

**Comment by lachmanfrantisek** [comment]
@fernflower , just for context:
We've discussed this once more (see [this Miro board](https://miro.com/app/board/uXjVMU0czD0=/?share_link_id=737881778611) if you are interested..;) Hopefully, you can set your Copr project as `repository` as Tomáš has described. So, please, try that and if it doesn't work, we can give you pointers on where/how the `additional_artifacts` can be implemented.

**Comment by lachmanfrantisek** [comment]
This use case is already supported and was resolved by a couple of fixes/improvements on the Testing Farm side.

Here's how `leapp` itself uses this: https://github.com/oamg/leapp/blob/7565b5c8cd5a098522565ff0ed5278eb2b04b7a8/.packit.yaml#L113-L121

Note that when specifying the repository, you can also list packages to be listed and the order of this package source.
