### ISSUE TITLE
race condition when handling TF results

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#2016]
Two hours passed, the check is still in progress.

![image](https://user-images.githubusercontent.com/1662493/233299776-0c577af5-401f-4d8d-b511-c2a08c16ccfc.png)

But it completed an hour ago in TF:

```
"2023-04-20T06:02:40.341+0000","Testing farm 45a372cc-0157-411c-9c8f-92d71cacdca1 result:
TestingFarmResult.passed"
"2023-04-20T06:02:40.343+0000","Testing farm results already processed (state in the DB is the same as the one about to report)."
"2023-04-20T06:02:40.343+0000","Cleaning up the mess."
"2023-04-20T06:02:40.343+0000","Removing contents of the PV."
"2023-04-20T06:02:40.343+0000","Job finished!"
"2023-04-20T06:02:40.343+0000","Pushing the metrics to pushgateway."
"2023-04-20T06:02:40.435+0000","Task TaskName.testing_farm_results[797cb8a4-0500-4968-836a-cc86b0324b98] succeeded in 0.10168441385030746s: {'job': {'tests-20230420060240341613': {'success': True, 'details': {...}}}, 'event': {'created_at': 1681970558, '_package_config_searched': True, 'project_url': 'https://github.com/teemtee/upgrade', '_pr_id': 10, 'fail_when_config_file_missing': False, 'actor': None, 'pipeline_id': '45a372cc-0157-411c-9c8f-92d71cacdca1', 'result': 'passed', 'compose': 'Fedora-37', 'summary': '', 'log_url': 'https://artifacts.dev.testing-farm.io/45a372cc-0157-411c-9c8f-92d71cacdca1', 'copr_build_id': '', 'copr_chroot': 'fedora-37-x86_64', 'commit_sha': 'f8d8d5eacf2f6fcb2661785715b0451d92b37931', 'created': '2023-04-20T05:56:05.709948Z', 'identifier': None, 'event_type': 'TestingFarmResultsEvent', 'trigger_id': 61617, 'task_accepted_time': None, 'pr_id': 10}}"
```

**Comment by lbarcziova** [comment]
I just had a look into [the Packit config](https://github.com/teemtee/upgrade/pull/10/files) of the affected repo and I can see there are 2 test jobs without identifiers that use different sets of targets. Therefore, since currently,  we don't check the targets when getting the matching job configuration for the TF results, this is what probably happened for the f37 results:
- we ran the reporting task twice (as there are two test jobs with matching (no) identifier) : 
    - first time for the first configured job (f36), the state in DB was updated, but nothing was reported in GH as the tested target didn't match the target in that configuration
   - second time for the second configured job (f37), the state in DB was already updated and therefore the reporting was skipped


I am not sure whether we have discussed this use case in the past and decided whether we should/should not support it (ping @TomasTomecek @lachmanfrantisek ), but using `identifier` for each test job here would solve the issue.

**Comment by Tiboris** [comment]
![drama](https://media.giphy.com/media/cM1iXk7jRzJS9NZrle/giphy.gif)

**Comment by lbarcziova** [comment]
There was a docs improvement to address this, I commented on the [affected PR](https://github.com/teemtee/upgrade/pull/10) and there is also a followup issue packit/packit#1964. Therefore closing this one.
