### ISSUE TITLE
Packit sometimes includes old version tarball in a sync_release commit

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#2181]
See this PR for example: https://src.fedoraproject.org/rpms/packit/pull-request/756#request_diff
I've seen this happen in packit before, and also in man-pages.

Opening in service, as I've never been able to reproduce the issue using CLI.

**Comment by lbarcziova** [comment]
Looks like this happened for a skipped upstream release when the particular tarball was not added to gitignore. But not sure why it was downloaded in the first place.

**Comment by lbarcziova** [comment]
I was not very successful with the logs and going through the code yet and I was not able to reproduce it either. As for the release when this happened in Packit, it also did not happen for all the updates, so it looks not deterministic. I added some debug logs in packit/packit#2108.

I suspect that the old tarball could be appended to the list of sources to download here because this is not logged anywhere (but it still should use the `sources` file from the particular branch):
https://github.com/packit/packit/blame/117cf6dd2cd59a7447e7299613357eaf8cbf7552/packit/base_git.py#L586-L592

I am also not sure why is the referenced part of the code actually needed, since later we go though the sources and patches from specfile and download those. Maybe @nforro do you have any idea?

**Comment by nforro** [comment]
> I am also not sure why is the referenced part of the code actually needed, since later we go though the sources and patches from specfile and download those. Maybe @nforro do you have any idea?

Sorry, I don't, I followed the existing logic when I was adapting the code for the specfile library.

BTW, here is another case of the issue:
https://src.fedoraproject.org/rpms/python-awscrt/pull-request/49#request_diff

**Comment by lbarcziova** [comment]
@nforro ok, thanks
