### ISSUE TITLE
ux: merge downstream without triggering build

### ISSUE THREAD

**Issue by LecrisUT** [packit/packit-service#2186]
### Description

There should be some mechanism to merge a packit PR (with `koji_build` job enabled) without triggering a koji build and/or use a new/specific tag. This is particularly important on rawhide where otherwise the builds need to be untagged to fix potential dependency issues.

### Importance

Medium. The packager can always create a new branch in their fork, but it would be a pain to do so.

### What is the impacted category (job)?

Fedora release automation

### Workaround

- [X] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [X] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lachmanfrantisek** [comment]
Hi @LecrisUT, what about using labels for that? (E.g. `packit-skip-koji-build`). (On the other hand, the info should ideally be in commit, not the PR.)

> Medium. The packager can always create a new branch in their fork, but it would be a pain to do so.

Good point, one can still recreate the PR.

**Comment by lachmanfrantisek** [comment]
Also, this should probably skip the build also if `allowed_pr_authors` is configure, right?

**Comment by LecrisUT** [comment]
Labels should be fine. It might be tricky if not all maintainers have the write privilege to the PR labels, but that's an organization issue for the package.

> On the other hand, the info should ideally be in commit, not the PR.

That would be tricky with `%autochangelog`

**Comment by lachmanfrantisek** [comment]
But we can start with the label and see how this works. Will you take a look at that, Cristian? It won't be hard I hope.

**Comment by LecrisUT** [comment]
I think I could navigate this issue. Probably will go through `ogr` to get the label. Otherwise it's in `packit-service` and not `packit` repo right?

**Comment by lachmanfrantisek** [comment]
> I think I could navigate this issue. Probably will go through `ogr` to get the label. Otherwise it's in `packit-service` and not `packit` repo right?

Yes, it should be in `packit-service`. Probably as a new checker here:

https://github.com/packit/packit-service/blob/9f79483be2e8d2368604da2bee03faf0fc003e3d/packit_service/worker/handlers/distgit.py#L579-L581

**Comment by lachmanfrantisek** [comment]
@LecrisUT just a gentle ping. Are you still interested in taking a look into this? (There is a related issue https://github.com/packit/packit/issues/1918 so I would like to know have we stand with this..)

**Comment by lachmanfrantisek** [comment]
When thinking about this again, we can:

* Have the label name configurable.
* When looking at https://github.com/packit/packit/issues/1918, it might be handy to support both allowing and disallowing so people can also trigger the build even if the PRs author is not configured. (=> So, have a pair of labels.)
* I hope labels (aka tags) are ok from the security point of view => labels do not require `commit` permissions to dist-git repo[0], but:
    * Someone with the admin rights needs to give the person `triage` permissions.
    * Someone with the `commit` permissions needs to configure this.
    
-----

[0]: Actually, the docs speak only about issue labels:
![image](https://github.com/packit/packit-service/assets/20214043/0b194147-2f64-4727-9943-1c1319c893a9)

**Comment by lachmanfrantisek** [comment]
Alternatively, we can use commits for that. (This has already been requested some time ago.)

This might work as follows:

1. We will react to a new dist-git commit (we wouldn't react to comments itself).
2. When checking the permissions, we will also go through the respective PR comments backwards (from newest to oldest) and if we find `/packit allow-koji-build` / `/packit disable-koji-build` (or some other names) and the comment author has `commit` rights to the repo, we will use this info instead of the permissions check to decide if the build should be triggered.

Implementation-wise, this might be a bit more complicated than with tags but still very easy thanks to OGR.

To me, the label looks more prominent and well-visible. And both comments and label actions are visible in the PR history:
![image](https://github.com/packit/packit-service/assets/20214043/4e14fd88-edeb-4a8b-bd7c-decd49f30e0e)

**Comment by LecrisUT** [comment]
Yeah, I think labels will be easier to manage, I'll take a look this coming week. Thanks for the reminder.

> - I hope labels (aka tags) are ok from the security point of view => labels do not require commit permissions to dist-git repo[0]

Should be fine because this should be checked when merging the PR.

> - When looking at https://github.com/packit/packit/issues/1918, it might be handy to support both allowing and disallowing so people can also trigger the build even if the PRs author is not configured. (=> So, have a pair of labels.)

Yeah, I can see how triggering build with label can be useful. I don't think it can address https://github.com/packit/packit/issues/1918 because the labels can only be on PRs, and you cannot make an empty commit PR in Pagure. I guess this can be partially resolved if we support non-empty PRs

**Comment by LecrisUT** [comment]
> > I think I could navigate this issue. Probably will go through `ogr` to get the label. Otherwise it's in `packit-service` and not `packit` repo right?
> 
> Yes, it should be in `packit-service`. Probably as a new checker here:
> 
> https://github.com/packit/packit-service/blob/9f79483be2e8d2368604da2bee03faf0fc003e3d/packit_service/worker/handlers/distgit.py#L579-L581

Some quick notes and questions looking at the implementation:
- Does `Checker.pre_check()` run at every event from `Pagure`? I shouldn't worry about any persistent configurations due to `Checker`?
- As I read it `Checker.pre_check()` only has value in early-exiting. That would work for `skip-build` label for this specific issue. But for `force-build` label there needs to be a hook to overwrite the default checks by packit that check if it __should__ trigger a build. Any clues on where to hook that?

**Comment by lbarcziova** [comment]
hi @LecrisUT !
> Does Checker.pre_check() run at every event from Pagure? I shouldn't worry about any persistent configurations due to Checker?

pre_check runs each time we create a handler (=> match event to some tasks that need to be run based on the configuration), see [this](https://github.com/packit/packit-service/blob/ff6c0f5f4ae9e51311fb8e195d2b2df3d325c4ac/packit_service/worker/jobs.py#L542)

> As I read it Checker.pre_check() only has value in early-exiting. That would work for skip-build label for this specific issue. But for force-build label there needs to be a hook to overwrite the default checks by packit that check if it should trigger a build. Any clues on where to hook that?

Not sure about this one, maybe you can explain the problem more, I would say with the right order of the checks we could  make it work.

> In Checker/any mixin, can I get the details of the event? This checks should only be run if the event is merge PR, and not if the event is comment. Currently I am looking at Checker.data.event_dict, but it doesn't seem to have the interface: 

yes, that's right, the `data.event_dict` will include the information about the event itself. But since with Koji build we react to new dist-git commits, it will be probably easier to get the PR via API and get the info about the labels from there. You can get inspired in how we check the PR author here:

https://github.com/packit/packit-service/blob/ff6c0f5f4ae9e51311fb8e195d2b2df3d325c4ac/packit_service/worker/checker/distgit.py#L43

**Comment by lbarcziova** [comment]
As I work on #2269, I will probably cover the labels implementation for this issue as well.
