### ISSUE TITLE
Make the status name customisable to use Packit in GitHub Merge Queues 

### ISSUE THREAD

**Issue by Mab879** [packit/packit-service#2266]
### Description

When using [GitHub Merge Queues ](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) you need have required jobs in your branch settings to cause failures to remove PRs from the queue. GitHub also requires the name of the required jobs to be the same on PRs and when ran on the branch so it can do this.

Currently the PR job title is something like `testing-farm:fedora-39-x86_64` but the branch job name is `testing-farm:<BRANCH NAME>:fedora-39-x86_64` this causes GitHub to kick the PR out of merge queue since it timeouts on waiting on PR job names (testing-farm:fedora-39-x86_64` ) to finish, which will never happen since the branch jobs are named differently. Thus rendering it impossible to use Packit with merge queues.

We would like some way to Packit tests with Merge Queues. However, I'm not 100% certain how solve this considering #1808. 

### Benefit

Users can use GitHub Merge Queues with Packit.

### What is the impacted category (job)?

General

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lachmanfrantisek** [comment]
Thanks @Mab879 for the details. It looks like we need to provide a way for users to set the status name. As with similar values, it might be good to provide variables for the user to construct anything.

@mfocko any idea how to make this work?

**Comment by mfocko** [comment]
> @mfocko any idea how to make this work?

~~:classic: Python programming… just add another railway junction to the code~~ I mean, handle this prefix specifically when constructing the status names…

**Comment by lachmanfrantisek** [comment]
I've slightly changed the title to cover what is needed from Packit side:
* [ ] Create a new config option (?`status_name`) in Packit repository.
* [ ] Use this config option in the service and provide a basic set of variables to template it.
* [ ] Document the functionality itself with all the variables but also the Merge Queues so people can find it easily when trying to set this up.

**Comment by mfocko** [comment]
*notes from the refinement discussion*

@mfocko: I would be careful about going with the `status_name`, since it _easily_ allows fixing this issue, **but** at the cost of potentially opening the “can of worms”, because it is customizable; we've reiterated to the current status checks naming because of various issues (Copr builds both on PR and on merge (branch push trigger); labels; stg v. prod), this makes it an _easy fix_ with consequences of multiple bugs caused by the service depending on the naming… Please take this in account.

As per the templating, I would base it off our current “scheme”:
* target/chroot, e.g. `centos-stream-10-x86_64`
* job type, e.g. `rpm-build`
* labels (wondering about the undefined, maybe `undefined` would actually do; also possibility of multiple labels being defined)
* trigger (branch name, `pr`, `release`, etc.)

**Comment by lsm5** [comment]
This would be desirable for the containers team too. We're now looking at adding CentOS Stream 10 downstream jobs so we now have to include the `packages` key which ends up appending to the job name, would be great to be able to silence that.
