### ISSUE TITLE
Make PACKIT_PROJECT_VERSION available in post-upstream-clone

### ISSUE THREAD

**Issue by xsuchy** [packit/packit-service#2313]
According to documentation https://packit.dev/docs/configuration/actions#environment-variables-set-by-packit
the variable is not available in Actions. 

I want to do something like:

```
actions:
  post-upstream-clone:
    - bash -c "git archive -v -o ${PACKIT_DOWNSTREAM_REPO}/rubygem-gherkin-${PACKIT_PROJECT_VERSION}-testdata.txz v${PACKIT_PROJECT_VERSION} testdata/"
 
```

**Comment by kapr200** [comment]
Did you mean the issue for the sync release jobs ?

**Comment by xsuchy** [comment]
I meant
```
PACKIT_PROJECT_VERSION — current version of the project (coming from git describe)
```
i.e. upstream version we extracted from upstream git tag.

**Comment by mfocko** [comment]
For which jobs do you want it though?

* for `sync-release` (`pull-from-upstream` or `propose-downstream`) it's available since April (https://github.com/packit/packit/commit/e1b80fcb31a449866ab51043137f6a12d0958cfa by @lbarcziova)
* if you want it for upstream part, e.g., Copr build, it can be added in the linked PR

**Comment by xsuchy** [comment]
I wanted it for `pull-from-upstream` for `post-upstream-clone` action.

**Comment by mfocko** [comment]
OK, based on the comment from @nforro , it appears to be solved in https://github.com/packit/packit/commit/e1b80fcb31a449866ab51043137f6a12d0958cfa by @lbarcziova, therefore closing as fixed.
