### ISSUE TITLE
Onboard authselect

### ISSUE THREAD

**Issue by pbrezina** [packit/packit-service#2372]
### What we are onboarding?

* https://github.com/authselect/authselect
* https://github.com/SSSD/sssd

### Do you have more details?

Both projects already have their spec file in upstream repositories:
authselect: rpm/authselect.spec.in
sssd: contrib/sssd.spec.in

**Comment by lachmanfrantisek** [comment]
Hi @pbrezina !

Thanks for being the brave first one to try this...;) We'll take a look.

Since you've linked the upstream projects (and you have access to it if I remember correctly), do you want to configure upstream jobs (Copr builds and/or tests) as well as the Fedora automation (=release syncing, Koji builds and Bodhi updates)?

**Comment by pbrezina** [comment]
Yes, we can do that. Both repos are under Red Hat's control, but let's do authselect first since I have full control there. SSSD is team project so doing changes there might be more difficult.

Thank you.

**Comment by pbrezina** [comment]
Thank you, I think we can close this now. I'll test it in authselect for a while, then add it to sssd.
