### ISSUE TITLE
It looks like the `TestingFarmResult` type in the DB is missing the `retry` member

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#2466]
It looks like commit https://github.com/packit/packit-service/commit/88ed4e7f41e1fc57af1fddbd4b4d22b08dd1b99d added `TestingFarmResult.retry` but without reflecting it in Alembic migration script.

Possibly as a result of https://github.com/packit/packit-service/pull/2464 there are now errors like this in worker logs:

```
(psycopg2.errors.InvalidTextRepresentation) invalid input value for enum testingfarmresult: "retry"
LINE 1: UPDATE tft_test_run_targets SET status='retry' WHERE tft_tes...
```

**Comment by lbarcziova** [comment]
I don't think #2464 affected this, from what I have checked so far, I think this happens when we are submitting the request to TF and get some exception, currently the `Bad request` one (the reason of this is still not clear to me), so we try to retry and hit the problem you described, with missing DB enum value, all happening in this method:
https://github.com/packit/packit-service/blob/5b37b72c2449b344836ea13fe90d817765655c95/packit_service/worker/helpers/testing_farm.py#L1091
