### ISSUE TITLE
Return OpenScanHub log files without download link

### ISSUE THREAD

**Issue by Venefilyn** [packit/packit-service#2644]
### Description

Currently all log files are download links, i.e. has `?format=raw` in the URL. As this will start a download it might not be the best to return that. Instead to me it would make more sense to return the URL without query parameters and if needed you can add it to any clients utilizing the API.

### Benefit

Less complexity, more freedom to handle links how we need to instead of formatting.

### Importance

For dashboard, medium priority. There is a workaround that can be done which would be to parse the URL and remove the `?format=raw` before displaying it.

### What is the impacted category (job)?

Other

### Workaround

- [X] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by mfocko** [comment]
Again, please go against OpenScanHub. Briefly checking the links that we have on dashboard, it might be just an issue of the HTTP server configuration, as without `?format=raw` I get a full page with styles and everything. With `?format=raw` it's just “raw” logs as the name suggests (though it might be handled by the server as a file to download rather than display).

**Comment by Venefilyn** [comment]
> Again, please go against OpenScanHub

Thought this was a Packit thing. Nonetheless, opened issue here #304. If it changes in the future I would want to see if we can update the DB to all be https for the older entries

**Comment by majamassarini** [comment]
We keep [this](https://github.com/packit/packit-service/issues/2642) card for updating the db.
Closing the issue since now it is on openscanhub side.
