### ISSUE TITLE
 [RFE] can we trigger koji-build (or other packit-service )  ? 

### ISSUE THREAD

**Issue by sergiomb2** [packit/packit-service#2651]
### Description

hello, last paragraph of https://packit.dev/docs/fedora-releases-guide/non-divergent-dist-git-branches says "You can work around this bug by manually retriggering the Koji build by commenting on the downstream merged pull request with /packit koji-build "  .

packit build in-koji doesn't do the bodhi update and packit create-update --dist-git-branch doesn't do the same of packit-service,  for example doesn't close the bugs on bugzilla.

Best regards,

### Benefit

more uniform automation 

### What is the impacted category (job)?

Fedora release automation

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lachmanfrantisek** [comment]
Hi @sergiomb2 ,

I hope you know this already, but Packit CLI is not a client for the Packit Service but a way to run this with your identity locally. (It's on the same level as service.)
Do you think we should make this somewhere more explicit?

Regarding the commands:
* You can configure the Packit service to create Bodhi updates for builds triggered by other packages (i.e. you): https://packit.dev/docs/configuration/downstream/bodhi_update#optional-parameters
* Same, you can configure the Pakit service to trigger builds for dist-git changes caused by other users:  https://packit.dev/docs/configuration/downstream/koji_build#optional-parameters (`allowed_pr_authors` and `allowed_committers`).


So, can these options help in your use case?
- If yes, we can mention it in the documentation part you've mentioned.
- If not, can you please suggest what would help you?

**Comment by lachmanfrantisek** [comment]
@sergiomb2 , if I understand you properly, you want to mention also a way how to overcome this problem via CLI?

We can easily add that. I am just not sure if this isn't too complicated and confusing compared to commenting on a pull-request.

* You need to install `packit` package locally and set up authentication.
* Once you run a job from CLI, the next steps won't be run by Packit Service (by default):
    * This is to not collide with manual interventions (e.g. from other packagers or even proven packagers).
    * You need to update the config with the two options I've mentioned above to let Packit now that it should run also for actions triggered by you.
* The locally-run jobs are not visible in the dashboard which might be confusing.

So, I can see two options:
1. Don't promote CLI in this case because it's much easier to comment on a dist-git pull request.
2. Mention a way to trigger jobs via CLI, but mention all the steps needed to make it work.

Witch one do you prefer? I slightly prefer the first one because it's easier and does not have any downsides.

**Comment by majamassarini** [comment]
> From the today's team discussion:
> 
> * We would like to create a new FAQ to describe using Packit CLI  together with Packit service and we can link it from places like this.

Also related with #1657

**Comment by sergiomb2** [comment]
> The locally-run jobs are not visible in the dashboard which might be confusing.

is more than confusing, doesn't do the same , the owners of builds are different, the user which create update is me and is not packit , I have do it in two steps [1] at least and  "packit create-update"  doesn't close bugs as packit service do .

On other hand one pull requests just to request packit service , is not a good option for me , history on git and of PRs will not be elegant  

[1]
packit build in-koji --dist-git-branch f40
packit create-update --dist-git-branch f40

**Comment by sergiomb2** [comment]
> Also related with #1657

"We should give maintainers the ability to overcome a failing automation." 

yes, definitively is what I'm asking in this issue , overcome a failing automation without hacking and with the same automation if it isn't much difficult. 

we have `packit build` and `packit create-update` but isn't the same in my point of view , maybe was meant to be , I don't know

**Comment by lachmanfrantisek** [comment]
> is more than confusing, doesn't do the same , the owners of builds are different, the user which create update is me and is not packit , I have do it in two steps [1] at least and "packit create-update" doesn't close bugs as packit service do .

That's exactly what I meant. Unless we have a real client CLI, we can't fix these issues.

> On other hand one pull requests just to request packit service , is not a good option for me , history on git and of PRs will not be elegant

Not sure if I fully follow, but you can use any dist-git PR to retrigger the job. And I don't think information about retriggering needs to be saved in git. It's like a "rerun" button.

But to have something actionable:
* Let's document the CLI specifics in a FAQ. (this issue)
* Do a proper documentation of overcoming failures in #1657

**Comment by sergiomb2** [comment]
> Not sure if I fully follow, but you can use any dist-git PR to retrigger the job. And I don't think information about retriggering needs to be saved in git. It's like a "rerun" button.

I see, we can use an old PR to retigger the job ? can I use one close PR ?  well, this ticket is just about retigger the job without use an (new) PR. 
OK, and if I want retrigger for an branch, let says f41 for example, do I need have a PR asking to merge f41 branch ? 

Thank you, 

Reading week 44,  https://packit.dev/posts/weekly/2024/week-44#week-44-october-29th--november-4th  I'll add this [1]  to almost all configuration , and I will see how it goes ... 

```
rawhide:
      fast_forward_merge_into: [fedora-branched]
```

**Comment by sergiomb2** [comment]
fast_forward_merge_into: [fedora-branched] worked well, now I got PR(s) for all branches , if something fail, I can use the PR in question to re-trigger any event . So everything is solved
Thank you
