### ISSUE TITLE
Rust use-case

### ISSUE THREAD

**Issue by ignatenkobrain** [packit/packit-service#436]
We heavily rely on release-monitoring.org to get information about updates for rust crates. Then it is about cloning repo, running `rust2rpm` and check few things. Mostly this is automated. It would be great if automation would run rust2rpm and send PR automatically when new version is detected.

**Comment by lachmanfrantisek** [comment]
> It won't be one command to run anyway, since I'll need to inspect licenses, patch dependencies and such.

OK, but the spec-changes can be reviewed in the PR.

> Also, from where would it download sources?

It will get it from the specfile. So, probably `crates.io`?

> What will happen to existing patches & changelog?

If you autogenerate the specfile, you probably don't have the patches.

If yes, you can use the [source-git](https://packit.dev/docs/how-to-source-git/) mechanism to have them somewhere in the form of git commits. Here is currently a problem that you don't want to maintain a thousand source-git repos. We are working on the automation of the source-git workflow (because of the centos-stream).

I probably need to look closer to some rust package to understand it better.

**Comment by ignatenkobrain** [comment]
Stop by #fedora-rust channel on freenode and one of rust-sig members can describe how we maintain that stuff and how it works.

**Comment by lachmanfrantisek** [comment]
This fits to our current source-git initiative. I am going to close this issue in favour of this Source-git SIG issue: https://pagure.io/fedora-source-git/sig/issue/16
