### ISSUE TITLE
Flagging PRs in Pagure

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#591]
There are flags for commits and PRs. How do we make it clear which commit the PR flags are referring too?

This issue is to track the discussion started in https://pagure.io/pagure/issue/4835.

**Comment by lachmanfrantisek** [comment]
The Pagure issue is being worked on. It looks like we can use commit-flag for flagging PRs like on GitHub. (So, we will be able to remove that pr-flag completely.)

**Comment by TomasTomecek** [comment]
what work on our side is this issue tracking exactly?

**Comment by lachmanfrantisek** [comment]
Isn't this about using commit flags instead of the PR flags?

So, remove the "hack" for Pagure from the service code:

https://github.com/packit/packit-service/blob/17e07017b640fe03efb5236c0dd51132727b8a6d/packit_service/worker/reporting.py#L94-L111

https://github.com/packit/packit-service/blob/17e07017b640fe03efb5236c0dd51132727b8a6d/packit_service/worker/reporting.py#L190-L192

**Comment by lachmanfrantisek** [comment]
It would be nice to get rid of the pagure-specific tweaks.

**Comment by lbarcziova** [comment]
Implemented in #1167
