### ISSUE TITLE
`/packit propose-update` in issue didn't trigger update for expected targets

### ISSUE THREAD

**Issue by sakalosj** [packit/packit-service#898]
Manual trigger via GitHub issue comment `/packit propose-update` didn't trigger for expected targets

https://github.com/abrt/will-crash/issues/33

**Comment by sakalosj** [comment]
I was not able to find any related logs in db. Any suggestions on where to find them?

**Comment by lachmanfrantisek** [comment]
They had updated the version manually when you commented on that PR. I'm guessing that the PRs have not been created because of the empty difference.

**Comment by sakalosj** [comment]
> They had updated the version manually when you commented on that PR. I'm guessing that the PRs have not been created because of the empty difference.

@lachmanfrantisek 
an empty difference of what?

**Comment by lachmanfrantisek** [comment]
> an empty difference of what?

Of the PR. That the PR did not contain any file change because the change had already been done manually. (But, we put some metadata about used packit version to the `README.packit` so it should have some change at least.)

**Comment by lbarcziova** [comment]
I looked into the events in Sentry and found [this](https://sentry.io/organizations/red-hat-0p/issues/1327833680/events/1fe03cf02acf4859b8b2fd9c302de643/?project=1767823&statsPeriod=14d) from yesterday 9:07:16 (the event is that issue comment `/packit propose-update`), [the one PR](https://src.fedoraproject.org/rpms/will-crash/pull-request/3#) is from 9:07:10, so probably `f33` was processed first, and then when processing `f32`, there was the exception (not caught) . Therefore just that one PR was created.

**Comment by lachmanfrantisek** [comment]
> and then when processing f32, there was the exception (not caught) .

@lbarcziova What do you suggest? Do we need to catch the exception?

**Comment by lbarcziova** [comment]
@lachmanfrantisek yes, the exception should be caught, because this way the user is not informed what really happened and why the PR was created only for the one branch.

But as I looked into the recent code changes, it was probably done in your last PR - the 2 handlers (comment and release trigger) were unified and now the general exception [is caught](https://github.com/packit/packit-service/blob/deaafcb7e98bb01f7a86aa9fd92f12ef57b988df/packit_service/worker/handlers/github_handlers.py#L185) also for the comment, so it is probably solved now.

**Comment by lachmanfrantisek** [comment]
Thanks, let's close and reopen if needed.
